export const categories = [
  {
    id: 1,
    name: "Classical",
  },
  {
    id: 2,
    name: "Baroque",
  },
  {
    id: 3,
    name: "Romantic",
  },
  {
    id: 4,
    name: "Late 19th",
  },
];

export const songs = [
  {
    id: 1,
    title: "Symphony No. 41 Jupiter, 1st Movement Allegro Vivace",
    category: "Classical",
    composer: "Wolfgang Amadeus Mozart",
    description:
      "Jupiter Symphony, byname of Symphony No. 41 in C Major, K 551, orchestral work by Austrian composer Wolfgang Amadeus Mozart, known for its good humour, exuberant energy, and unusually grand scale for a symphony of the Classical period.",
    price: "30",
    published: "1788",
    newArrival: true,
    img: "img_1.jpg",
    mp3: "m1.mp3",
  },
  {
    id: 2,
    title: "Scherzo: Allegro vivace con delicatezza",
    category: "Classical",
    composer: "Schubert, Franz",
    description:
      "In the first part of the Classical period, the dance movement, when it appeared, usually consisted of a minuet in fairly simple binary form (the two-part form from which sonata form evolved)...",
    price: "80",
    published: "1828",
    newArrival: false,
    img: "img_2.jpg",
    mp3: "m2.mp3",
  },
  {
    id: 3,
    title: "Bach, J.S.: Goldberg Variations, BWV 988",
    category: "Baroque",
    composer: "J.S. Bach",
    description:
      "On his visits to Dresden, Bach had won the regard of the Russian envoy, Hermann Karl, Reichsgraf (count) von Keyserlingk, who commissioned the so-called Goldberg Variations; these were published in 1741...",
    price: "100",
    published: "1741",
    newArrival: false,
    img: "img_4.jpg",
    mp3: "m3.mp3",
  },
  {
    id: 4,
    title: "Mussorgsky, Modest: Night on Bald Mountain",
    category: "Classical",
    composer: "Mussorgsky, Modest",
    description:
      "Night on Bald Mountain, Russian Noch na lysoy gore, also called Night on Bare Mountain, orchestral work by the Russian composer Modest Mussorgsky that was completed in June 1867...",
    price: "40",
    published: "1867",
    newArrival: false,
    img: "img_3.jpg",
    mp3: "m4.mp3",
  },
  {
    id: 5,
    title: "Claudio Monteverdi: Madrigals",
    category: "Baroque",
    composer: "Claudio Monteverdi's Madrigals",
    description:
      "Claudio Giovanni Antonio Monteverdi was an Italian composer, gambist, singer and Roman Catholic priest. Monteverdi's work, often regarded as revolutionary, marked the transition from the Renaissance style of music to that of the Baroque period...",
    price: "200",
    published: "1587-1651",
    newArrival: false,
    img: "img_5.jpg",
    mp3: "m5.mp3",
  },
  {
    id: 6,
    title: "Bach: Concerto No. 1 in D Major",
    category: "Baroque",
    composer: "Bach",
    description:
      "Baroque music, a style of music that prevailed during the period from about 1600 to about 1750, known for its grandiose, dramatic, and energetic spirit but also for its stylistic diversity...",
    price: "140",
    published: "1791",
    newArrival: false,
    img: "img_6.jpg",
    mp3: "m6.mp3",
  },
  {
    id: 7,
    title: "Frederic Chopin: Piano Concerto No. 1 in E Minor",
    category: "Romantic",
    composer: "Frederic Chopin",
    description:
      "A second concert confirmed his success, and on his return home he prepared himself for further achievements abroad by writing his Piano Concerto No. 2 in F Minor (1829) and his Piano Concerto No. 1 in E Minor (1830)...",
    price: "130",
    published: "1830",
    newArrival: false,
    img: "img_7.jpg",
    mp3: "m7.mp3",
  },
  {
    id: 8,
    title: "Franz Liszt: Christus",
    category: "Late 19th",
    composer: "Franz Liszt",
    description:
      "For the next eight years Liszt lived mainly in Rome and occupied himself more and more with religious music. He completed the oratorios Die Legende von der heiligen Elisabeth (1857-62) and Christus (1855-66) and a number of smaller works...",
    price: "199",
    published: "1855-1866",
    newArrival: false,
    img: "img_8.jpg",
    mp3: "m8.mp3",
  },
  {
    id: 9,
    title: "Claude Debussy: Children's Corner",
    category: "Romantic",
    composer: "Claude Debussy",
    description:
      "Repelled by the gossip and scandal arising from this situation, he sought refuge for a time at Eastbourne, on the south coast of England. For his daughter, nicknamed Chouchou, he wrote the piano suite Children's Corner (1908)...",
    price: "149",
    published: "1908",
    newArrival: false,
    img: "img_9.jpg",
    mp3: "m9.mp3",
  },
  {
    id: 10,
    title: "Robert Schumann: Papillons",
    category: "Romantic",
    composer: "Robert Schumann",
    description:
      "In the summer of 1829 he left Leipzig for Heidelberg. There he composed waltzes in the style of Franz Schubert, afterward used in his piano cycle Papillons (Opus 2; 1829-31), and practiced industriously...",
    price: "131",
    published: "1831",
    newArrival: false,
    img: "img_10.jpg",
    mp3: "m10.mp3",
  },
  {
    id: 11,
    title: "Symphony No. 3",
    category: "Late 19th",
    composer: "Gustav Mahler",
    description:
      "Symphony No. 3, symphony for orchestra and choruses by Austrian composer Gustav Mahler that purports to encapsulate everything the composer had learned about life to date...",
    price: "80",
    published: "1902",
    newArrival: false,
    img: "img_11.jpg",
    mp3: "m11.mp3",
  },
  {
    id: 12,
    title: "Liszt: Bagatelle sans tonalite",
    category: "Late 19th",
    composer: "Liszt",
    description:
      "In 1869 Liszt was invited to return to Weimar by the grand duke to give master classes in piano playing, and two years later he was asked to do the same in Budapest...",
    price: "103",
    published: "1872",
    newArrival: false,
    img: "img_12.jpg",
    mp3: "m12.mp3",
  },
];
